export PYTHONPATH="$PYTHONPATH:$PWD"
export PYTHONPATH="$PWD/3rdparty/tenspiler:$PYTHONPATH"
export PATH="$PWD/3rdparty/racket/bin/:$PATH"
export PATH="$PWD/3rdparty/cvc5/build/bin/:$PATH"
export LD_LIBRARY_PATH="$PWD/3rdparty/cadical/build/:$LD_LIBRARY_PATH"
export PATH="$PWD/3rdparty/bitwuzla/build/bin:$PATH"